/**
 * Runs every scenario over both transports, judges the results against the expectations, and
 * writes them down: a table on stdout, `bench/results/harness.json`, and the Markdown fragments
 * the Performance chapter includes.
 *
 * Started by `bench/run.mjs`, which bundles this file and passes the repository root as the first
 * argument and `--expose-gc` to Node. Exits with 1 when a scenario does not do what it measures or
 * when a measurement has no expectation - never because a number is worse than expected: what
 * to do about that is a decision for a person (ADR-0023), and the chapter
 * records it.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { cpus, release, version } from 'node:os';
import { join } from 'node:path';
import { performance } from 'node:perf_hooks';
import process from 'node:process';

import { distSizes, kilobytes } from '../../scripts/dist-sizes.mjs';
import { TRANSPORT_MODES } from '../../test/harness/browser-harness.js';
import { describeCommit } from '../commit.js';
import { HARNESS_EXPECTATIONS } from '../expectations.js';
import {
  farWorse,
  formatMarkdown,
  formatTable,
  judgeScenario,
  type BenchRun,
  type ScenarioResult,
} from '../report.js';

import { SCENARIOS } from './scenarios.js';

const root = repositoryRoot();

const startedAt = performance.now();
const scenarios: ScenarioResult[] = [];
for (const transport of TRANSPORT_MODES) {
  for (const scenario of SCENARIOS) {
    const before = performance.now();
    const measured = await scenario.run(transport);
    scenarios.push(
      judgeScenario(
        HARNESS_EXPECTATIONS,
        measured.id,
        transport,
        measured.samples,
        measured.values,
        measured.note,
      ),
    );
    process.stderr.write(
      `${measured.id} (${transport}): ${((performance.now() - before) / 1000).toFixed(1)} s\n`,
    );
  }
}

const run: BenchRun = {
  kind: 'harness',
  date: new Date().toISOString().slice(0, 10),
  commit: describeCommit(root),
  machine: {
    os: `${version()} (${release()})`,
    cpu: cpus()[0]?.model.trim() ?? 'unknown CPU',
    runtime: `Node ${process.versions.node}`,
    device: 'the harness fake (`test/harness/fake-serial.ts`)',
  },
  scenarios,
};

mkdirSync(join(root, 'bench', 'results'), { recursive: true });
mkdirSync(join(root, 'docs', 'site', '_generated'), { recursive: true });
writeFileSync(join(root, 'bench', 'results', 'harness.json'), `${JSON.stringify(run, null, 2)}\n`);
writeFileSync(
  join(root, 'docs', 'site', '_generated', 'harness-benchmark.md'),
  formatMarkdown(run),
);
writeFileSync(join(root, 'docs', 'site', '_generated', 'build-sizes.md'), sizesMarkdown());

process.stdout.write(`\n${formatTable(run)}`);
const worst = farWorse(run);
process.stdout.write(
  worst.length === 0
    ? '\nNo result is more than ten times worse than its expectation.\n'
    : `\n${String(worst.length)} result(s) more than ten times worse than expected - each needs a fix or a documented limit (docs/site/performance.md):\n${worst
        .map(
          (metric) =>
            `- ${metric.scenario.id} (${metric.scenario.transport}) ${metric.key}: ${String(metric.measured)} ${metric.unit} against ${String(metric.expected)} ${metric.unit}\n`,
        )
        .join('')}`,
);
process.stdout.write(
  `Ran in ${((performance.now() - startedAt) / 1000).toFixed(0)} s; results in bench/results/harness.json and docs/site/_generated/.\n`,
);

function repositoryRoot(): string {
  const argument = process.argv[2];
  if (argument === undefined) {
    throw new Error('bench/harness/main.ts expects the repository root as its first argument');
  }
  return argument;
}

/** The build sizes as a Markdown table, or a sentence saying that there is no build. */
function sizesMarkdown(): string {
  const sizes = distSizes(root);
  const lines = [
    '<!-- Generated by `npm run bench` from `scripts/dist-sizes.mjs`. Do not edit; run it again. -->',
    '',
  ];
  if (sizes.length === 0) {
    lines.push('No build was present when the benchmark ran: `npm run build` first.');
  } else {
    lines.push('| File | Built | Gzipped |', '| --- | --- | --- |');
    for (const { file, bytes, gzip } of sizes) {
      lines.push(`| \`${file}\` | ${kilobytes(bytes)} | ${kilobytes(gzip)} |`);
    }
  }
  return `${lines.join('\n')}\n`;
}
